{
 "title": "goim-dashboard",
 "description": "goim metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "goim_comet_goroutines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "go_goroutines{job=\"goim-comet\"}"
    }
   ]
  },
  {
   "title": "goim_logic_goroutines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{job=\"goim-logic\"}"
    }
   ]
  },
  {
   "title": "goim_job_goroutines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{job=\"goim-job\"}"
    }
   ]
  },
  {
   "title": "goim_comet_online",
   "type": "singlestat",
   "description": "pepole of online number",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goim_comet_online{job=\"goim-comet\"}"
    }
   ]
  },
  {
   "title": "goim_comet_tcponline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "goim_comet_tcponline" }
   ]
  },
  {
   "title": "goim_comet_wsonline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goim_comet_wsonline{job=\"goim-comet\"}"
    }
   ]
  },
  {
   "title": "goim_comet_memstats",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total{job=\"goim-comet\"}",
     "legendFormat": "Total number of bytes allocated, even if freed."
    },
    {
     "expr": "go_memstats_frees_total{job=\"goim-comet\"}",
     "legendFormat": "Total number of frees."
    }
   ]
  },
  {
   "title": "goim_scrape_duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"goim-comet\",instance=\"109.10.21.217:8005\"}",
     "legendFormat": "comet"
    },
    {
     "expr": "scrape_duration_seconds{job=\"goim-logic\",instance=\"109.10.21.217:8015\"}",
     "legendFormat": "logic"
    },
    {
     "expr": "scrape_duration_seconds{job=\"goim-job\",instance=\"109.10.21.217:8025\"}",
     "legendFormat": "job"
    }
   ]
  },
  {
   "title": "goim_job_cometnodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "goim_job_cometnodes{job=\"goim-job\"}"
    }
   ]
  },
  {
   "title": "goim_job_activeroomcount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "goim_job_activeroomcount{job=\"goim-job\"}"
    }
   ]
  },
  {
   "title": "goim_comet_msg_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "goim_comet_allmsg{job=\"goim-comet\"}",
     "legendFormat": "comet_allmsg"
    },
    {
     "expr": " goim_comet_pushmsg{job=\"goim-comet\"}",
     "legendFormat": "pushmsg"
    },
    {
     "expr": "goim_comet_broadcastroommsg{job=\"goim-comet\"}",
     "legendFormat": "broadcastroommsg"
    },
    {
     "expr": "goim_comet_broadcastmsg{job=\"goim-comet\"}",
     "legendFormat": "broadcastmsg"
    }
   ]
  },
  {
   "title": "goim_job_msg_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "goim_job_allmsg", "legendFormat": "allmsg" },
    { "expr": "goim_job_pushmsg", "legendFormat": "pushmsg" },
    { "expr": "goim_job_broadcastroommsg", "legendFormat": "broadcastroommsg" },
    { "expr": "goim_job_broadcastmsg", "legendFormat": "broadcastmsg" }
   ]
  }
 ]
}