kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: details
  namespace: bookinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookinfo-details
  template:
    metadata:
      labels:
        app: bookinfo-details
    spec:
      containers:
        - name: details
          image: {{ .Values.images.details }}
          ports:
           - containerPort: 5001
             protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /debug/pprof/symbol
              port: 5003
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2