kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: redis
  namespace: bookinfo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: bookinfo
      type: bookinfo-nosql-redis
  template:
    metadata:
      labels:
        app: bookinfo
        type: bookinfo-nosql-redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2