version: '2'
services:
  kafka.server:
    image: kafka
    ports:
      - 3406:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=goim
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin

  redis.server:
    image: redis
    ports:
      - 6973:6379/tcp

  promethrus:
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - /home/goim/deploy/docker/prometheus/data:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411/tcp

  goim-comet:
    image: gxlz/golang:1.10.3-apline3.7
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8005:8005
      - 8009:8009
    volumes:
      - $GOPATH/src/goim/comet:/go/src/goim/comet
    depends_on:
      - mysql.server
      - redis.server
      - promethrus
      - zipkin
    links:
      - mysql.server
      - redis.server
      - goim-logic
      - zipkin
    entrypoint:
      - ash
      - -c
      - |
        sleep 15 && \
        cd /go/src/goim/comet/cmd && \
        echo "RUN_MODE: container" > .env && \
        echo "MIGRATE: yes" >> .env && \
        realize start

  goim-logic:
    image: gxlz/golang:1.10.3-apline3.7
    ports:
      - 8011:8011
      - 8012:8012      
      - 8015:8015
    volumes:
      - $GOPATH/src/goim/logic:/go/src/goim/logic
    depends_on:
      - mysql.server
      - redis.server
      - promethrus
      - zipkin
    links:
      - mysql.server
      - redis.server
      - zipkin
    entrypoint:
      - ash
      - -c
      - |
        sleep 15 && \
        cd /go/src/goim/logic/cmd && \
        echo "RUN_MODE: container" > .env && \
        echo "MIGRATE: yes" >> .env && \
        realize start

  goim-job:
    image: gxlz/golang:1.10.3-apline3.7
    ports:
      - 8025:8025
    volumes:
      - $GOPATH/src/goim/job:/go/src/goim/job
    depends_on:
      - mysql.server
      - redis.server
      - promethrus
      - zipkin
    links:
      - mysql.server
      - redis.server
      - zipkin
    entrypoint:
      - ash
      - -c
      - |
        sleep 15 && \
        cd /go/src/goim/job/cmd && \
        echo "RUN_MODE: container" > .env && \
        echo "MIGRATE: yes" >> .env && \
        realize start