service_name: goim-job
runmode: "dev"
maxproc: 32
serverTick: "5s"
onlineTick: "10s"
logpath: ""
env:
  region: "bj"
  zone: "bj01"
  weight: 10
comet:
  dail: "1s"
  timeout: "1s"
  routinechan: 10
  routinesize: 10
discovery:
  addr: 109.254.2.139:8500
metrics_server:
  addr: :8025
zipkin:
  url: http://109.254.2.159:9411
  service_name: goim-job
  reporter:
    timeout: 5
    batch_size: 1000
    batch_interval: 3
    max_backlog: 3000
kafka:
  topic: goim-topic
  group: goim-group
  brokers:
    - 109.254.2.139:9092